### ISSUE TITLE
The Favicons & Apple icons need the new dark blue color

### ISSUE THREAD

**Issue by DawnAngel** [nats-io/nats-theme#4]
These icons still in the old theme color, take a look :)

**Comment by chriscasper** [comment]
I'll try to get these updated soon!

**Comment by mcqueary** [comment]
@DawnAngel Thanks for bringing it up, Eric; we will soon be "re-relaunching" the site with a new logo and will take care of the favicon then.

**Comment by chriscasper** [comment]
Site has been updated with the new logo and favicon.
